#!/bin/sh

echo "Enforcing Policies..."

line=`head -n1 $1`
if ! [[ $line =~ .*CC-[0-9]+.* ]]; then  
	echo "Commit message does not reference an issue."
	echo "See commit message: \"$line\""
	exit 1
fi
